config/routes.rb
Rails.application.routes.draw do

  resources :deputies
  
  #devise_for :users
  resources :charges
  resources :sensors
  resources :idea_crowdratings
  resources :prices
  resources :crits
  resources :idea_ratings
  resources :criterias
  resources :ideas
  resources :plannings
  resources :timetracks
  resources :user_answers
  resources :answers
  resources :questions
  resources :mlikes
  resources :comments
  resources :edition_arcticles
  resources :editions
  resources :qrcodes
  resources :signage_hits
  resources :signage_cals
  get 'rooms/show'

  resources :credentials
  root 'home#index3'
  
  resources :webmasters
  resources :user_tickets
  resources :user_positions
  resources :transactions
  get 'ticketuserview/index'
  get 'ticketuserview/index2'
  get 'users/ticketstatus'
  resources :tickets
  get 'statement/index'

  get 'showcal/index'
  get 'home/nutzung'
  get 'home/index'
  get 'home/index1'
  #get 'home/index1/:ticket_id', to: 'home#index1'
  get 'home/index2'
  get 'home/index3'
  get 'home/index6'
  get 'home/index7'
  get 'home/index8'
  get 'home/index9'
  get 'home/index10'
  get 'home/index11'
  get 'home/index12'
  get 'home/index13'
  get 'home/index14'
  get 'home/index15'
  get 'home/index16'
  get 'home/index17'
  get 'home/index18'
  get 'home/import'
  get 'home/dashboard'
  get 'home/dashboard2'
  get 'home/dashboard_project'
  get 'home/dashboard_data'
  get 'home/dashboard2_data'
  get 'home/dashboard_projectdata'
  get 'home/Umfragen_data'
  get 'home/readsensordata'
  get 'home/writesensordata'
  
  resources :searches
  resources :partner_links
  resources :mstats
  resources :msponsors
  resources :mratings
  resources :mobjects
  resources :mdetails
  resources :mcategories
  resources :mcalendars
  resources :madvisors
  get 'listaccount/index'

  resources :favourits
  resources :emails
  resources :customers
  get 'customer_advisor/index'

  get 'customer_advisor/index2'
  get 'appparams/updateuser'
  
  resources :companies
  resources :appparams
  resources :appointments
  resources :appointment_documents
  resources :accounts
  root 'home#index3'

  #devise_for :users, :controllers => {registrations: 'registrations'}
  #devise_for :users, :controllers => {registrations: 'registrations', passwords: 'passwords', confirmations: "confirmations"}
  devise_for :users, :controllers => {registrations: 'registrations', passwords: 'passwords'}
  
  resources :users
  resources :tests
  
  # mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
    belongs_to :question
    has_many :user_answers, dependent: :destroy  
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
    @answer.question_id = params[:question_id]
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to mobject_path(:id => @answer.question.mobject_id, :topic => "objekte_fragen"), notice: (I18n.t :act_create) }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to mobject_path(:id => @answer.question.mobject_id, :topic => "objekte_fragen"), notice: (I18n.t :act_update) }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer_question_mobject_id = @answer.question.mobject_id
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to mobject_path(:id => @answer_question_mobject_id, :topic => "objekte_fragen"), notice: (I18n.t :act_delete) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:question_id, :description, :name, :num)
    end
end

app/views/answers/_form.html.erb
    <%= form_for @answer do |f| %>

        <% if @answer.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@answer.errors.count, "error") + " " + (I18n.t :notsaved) %></h2>
              <ul>
                  <% @answer.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
              </ul>
            </div>
        <% end %>

        <div class="row">
            <div class="col-md-6">
                <div class="panel panel-default">
                    <div class="panel-heading header">
                      <li_header>
                      <%= (I18n.t :antwort) + " " + @answer.question.name %>
                      </li_header>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="panel-body">
                    <% case @answer.question.mcategory.name.upcase %>
                      <% when "multiple".upcase, "single".upcase %>
                        <div class="form-group">
                          <%= f.label (I18n.t :antwortoption) %>
                          <%= f.text_field :name, class:"form-control"%>
                        </div>
                    <% end %>
                    <%= f.hidden_field :question_id, class:"form-control" %>
                    <div class="actions">
                      <%= f.submit (I18n.t :speichern),  class:"btn btn-primary btn-lg"%>
                    </div>
                </div>
            </div>
        </div>
    <% end %>

app/views/answers/edit.html.erb
<%= render 'form', answer: @answer %>

app/views/answers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Answers</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Description</th>
      <th>Name</th>
      <th>Num</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.question_id %></td>
        <td><%= answer.description %></td>
        <td><%= answer.name %></td>
        <td><%= answer.num %></td>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<%= render 'form', answer: @answer %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @answer.question_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @answer.description %>
</p>

<p>
  <strong>Name:</strong>
  <%= @answer.name %>
</p>

<p>
  <strong>Num:</strong>
  <%= @answer.num %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>