config/routes.rb
Rails.application.routes.draw do

  resources :deputies
  
  #devise_for :users
  resources :charges
  resources :sensors
  resources :idea_crowdratings
  resources :prices
  resources :crits
  resources :idea_ratings
  resources :criterias
  resources :ideas
  resources :plannings
  resources :timetracks
  resources :user_answers
  resources :answers
  resources :questions
  resources :mlikes
  resources :comments
  resources :edition_arcticles
  resources :editions
  resources :qrcodes
  resources :signage_hits
  resources :signage_cals
  get 'rooms/show'

  resources :credentials
  root 'home#index3'
  
  resources :webmasters
  resources :user_tickets
  resources :user_positions
  resources :transactions
  get 'ticketuserview/index'
  get 'ticketuserview/index2'
  get 'users/ticketstatus'
  resources :tickets
  get 'statement/index'

  get 'showcal/index'
  get 'home/nutzung'
  get 'home/index'
  get 'home/index1'
  #get 'home/index1/:ticket_id', to: 'home#index1'
  get 'home/index2'
  get 'home/index3'
  get 'home/index6'
  get 'home/index7'
  get 'home/index8'
  get 'home/index9'
  get 'home/index10'
  get 'home/index11'
  get 'home/index12'
  get 'home/index13'
  get 'home/index14'
  get 'home/index15'
  get 'home/index16'
  get 'home/index17'
  get 'home/index18'
  get 'home/import'
  get 'home/dashboard'
  get 'home/dashboard2'
  get 'home/dashboard_project'
  get 'home/dashboard_data'
  get 'home/dashboard2_data'
  get 'home/dashboard_projectdata'
  get 'home/Umfragen_data'
  get 'home/readsensordata'
  get 'home/writesensordata'
  
  resources :searches
  resources :partner_links
  resources :mstats
  resources :msponsors
  resources :mratings
  resources :mobjects
  resources :mdetails
  resources :mcategories
  resources :mcalendars
  resources :madvisors
  get 'listaccount/index'

  resources :favourits
  resources :emails
  resources :customers
  get 'customer_advisor/index'

  get 'customer_advisor/index2'
  get 'appparams/updateuser'
  
  resources :companies
  resources :appparams
  resources :appointments
  resources :appointment_documents
  resources :accounts
  root 'home#index3'

  #devise_for :users, :controllers => {registrations: 'registrations'}
  #devise_for :users, :controllers => {registrations: 'registrations', passwords: 'passwords', confirmations: "confirmations"}
  devise_for :users, :controllers => {registrations: 'registrations', passwords: 'passwords'}
  
  resources :users
  resources :tests
  
  # mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  # GET /transactions
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1
  def show
  end

  # GET /transactions/new
  def new
    
    @transaction = Transaction.new
    if params[:user_id]
      @transaction.owner_id = params[:user_id]
      @transaction.owner_type = "User"
    end
    if params[:company_id]
      @transaction.owner_id = params[:company_id]
      @transaction.owner_type = "Company"
    end
    @transaction.ttype = "Payment"
    @transaction.trx_date = Date.today
    @transaction.valuta = Date.today
    @transaction.amount = params[:amount]
    @transaction.account_bel = params[:account_bel]
    @transaction.status = "erfasst"
    @transaction.ref = params[:ref]
    @transaction.text = ""

    @transaction.object_id = params[:object_id].to_i
    @transaction.object_name = params[:object_name]
    @item = Object.const_get(params[:object_name]).find(params[:object_id])
    
    # Vergütungskonto 
    if params[:user_id_ver]
      @user = User.find(params[:user_id_ver])
      @partners = Company.where('partner=?',true)
      @partners.each do |p|
        @customer = @user.customers.where("partner_id=?", p.id).first
        if @customer
          @account = @customer.accounts.where('is_account_ver=?',true).first
          if @account != nil
            @transaction.account_ver = @account.id
            @bv_1 = @user.name + " " + @user.lastname
            @bv_2 = @account.name
            @bv_3 = @account.iban
          end
        end
      end
    end
    if params[:company_id_ver]
      @company = Company.find(params[:company_id_ver])
      @partners = Company.where('partner=?',true)
      @partners.each do |p|
        @customer = @company.customers.where("partner_id=?", p.id).first
        if @customer
          @account = @customer.accounts.where('is_account_ver=?',true).first
          if @account != nil
            @transaction.account_ver = @account.id
            @bv_1 = @company.name
            @bv_2 = @account.name
            @bv_3 = @account.iban
          end
        end
      end
    end
    if !@account
      redirect_to @item, notice: 'no counterpart account defined, trx not possible'
      return
    end
    
  end

  # GET /transactions/1/edit
  def edit
    @account = Account.find(@transaction.account_ver)
    if params[:user_id]
      @user = User.find(params[:user_id])
      @ali = []
      @partners = Company.where('partner=?',true)
      @partners.each do |p|
        @customer = @user.customers.where("partner_id=?", p.id).first
        if @customer
          @customer.accounts.each do |ca|
            @ali << ca.id
          end
        end
      end
    end
    if params[:company_id]
      @company = Company.find(params[:company_id])
      @ali = []
      @partners = Company.where('partner=?',true)
      @partners.each do |p|
        @customer = @company.customers.where("partner_id=?", p.id).first
        if @customer
          @customer.accounts.each do |ca|
            @ali << ca.id
          end
        end
      end
    end
  end

  # POST /transactions
  def create
    @transaction = Transaction.new(transaction_params)
    if @transaction.save
      if @transaction.owner_type == "User" 
        redirect_to user_path(:id => @transaction.owner_id, :topic => "Transaktionen"), notice: (I18n.t :act_create)
      else
        redirect_to company_path(:id => @transaction.owner_id, :topic => "Transaktionen"), notice: 'Trx was successfully created.'
      end
    else
      render :new
    end
  end

  # PUT /transactions/1
  def update
    if @transaction.update(transaction_params)
      if @transaction.owner_type == "User" 
        redirect_to user_path(:id => @transaction.owner_id, :topic => "Transaktionen"), notice: (I18n.t :act_update)
      else
        redirect_to company_path(:id => @transaction.owner_id, :topic => "Transaktionen"), notice: (I18n.t :act_update)
      end
    end
  end

  # DELETE /transactions/1
  def destroy
    @owner_id = @transaction.owner_id
    @owner_type = @transaction.owner_type
    @transaction.destroy
    if @owner_type == "User"
      redirect_to user_path(:id => @owner_id, :topic => "Transaktionen"), notice: (I18n.t :act_delete)
    end
    if @owner_type == "Company"
      redirect_to company_path(:id => @owner_id, :topic => "Transaktionen"), notice: (I18n.t :act_delete)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:account_ver, :account_bel, :valuta, :trx_date, :owner_id, :owner_type, :ttype, :status, :active, :text, :ref, :amount, :object_name, :object_id)
    end

end

app/views/transactions/_form.html.erb
    <%= form_for @transaction do |f| %>

        <% if @transaction.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this calender from being saved:</h2>
              <ul>
                  <% @transaction.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
              </ul>
            </div>
        <% end %>

        <div class="row">
            <div class="col-md-6">
                <div class="panel panel-default">
                    <div class="panel-heading header">
                      <li_header>
                        <% if @transaction.owner_type == "User" %>
                            <%= link_to user_path(:id => @transaction.owner_id, :topic => "Transaktionen") do %>
                              <i class="btn btn-primary glyphicon glyphicon-list"></i>
                            <% end %>
                        <% end %>
                        <% if @transaction.owner_type == "Company" %>
                          <%= link_to company_path(:id => @transaction.owner_id, :topic => "Transaktionen") do %>
                            <i class="btn btn-primary glyphicon glyphicon-list"></i>
                          <% end %>
                        <% end %>
                        ZAHLUNG zu Gunsten <%= @transaction.owner.name %>
                      </li_header>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="panel-body">

                    <div class="form-group">
                      <%= f.label "Betrag" %><br>
                      <%= f.number_field :amount, class:"form-control" %>
                    </div>
                    <div class="form-group">
                      <%= f.label "Referenz" %><br>
                      <%= f.text_field :ref, class:"form-control" %>
                    </div>
                    <div class="actions">
                       <%= f.submit "Speichern", class:"btn btn-primary btn-lg"%>
                    </div>

                    <% @account_ver = Account.find(@transaction.account_ver) %>
                    <div class="form-group">
                      <%= f.label "Bankverbindung" %><br>
                      <% if @account_ver.customer.owner_id %>
                        <%= showImage2(:small, @account_ver.customer.owner, true) %>
                        <% if @account_ver.customer.owner_type == "User" %>
                          <%= @account_ver.customer.owner.name + " " + @account_ver.customer.owner.lastname %><br>
                        <% else %>
                          <%= @account_ver.customer.owner.name %><br>
                        <% end %>
                        <%= @account_ver.name %><br>
                        <%= @account_ver.iban %><br>
                      <% end %>
                    </div>
                    
                    <% @account_bel = Account.find(@transaction.account_bel) %>
                    <div class="form-group">
                      <%= f.label "Belastungskonto" %><br>
                      <% if @account_bel.customer.owner_id %>
                        <%= showImage2(:small, @account_bel.customer.owner, true) %>
                        <% if @account_bel.customer.owner_type == "User" %>
                          <%= @account_bel.customer.owner.name + " " + @account_bel.customer.owner.lastname %><br>
                        <% else %>
                          <%= @account_bel.customer.owner.name %><br>
                        <% end %>
                        <%= @account_bel.name %><br>
                        <%= @account_bel.iban %><br>
                      <% end %>
                    </div>

                    <div class="form-group">
                      <%= f.label "Text" %><br>
                      <%= f.text_area :text, :rows => 5, class:"form-control" %>
                    </div>
                    <div class="form-group">
                      <%= f.label "Zahlungsdatum" %><br>
                      <%= f.text_field :trx_date, class:"form-control" %>
                    </div>
                    <div class="form-group">
                      <%= f.label "Valutadatum" %><br>
                      <%= f.text_field :valuta, class:"form-control" %>
                    </div>
                    <%= f.hidden_field :account_ver, class:"form-control"  %>
                    <%= f.hidden_field :account_bel, class:"form-control"  %>
                    <%= f.hidden_field :owner_id, class:"form-control"  %>
                    <%= f.hidden_field :owner_type, class:"form-control"  %>
                    <%= f.hidden_field :ttype, class:"form-control"  %>
                    <%= f.hidden_field :status, class:"form-control"  %>
                    <%= f.hidden_field :active, class:"form-control"  %>
                    <%= f.hidden_field :object_name, class:"form-control"  %>
                    <%= f.hidden_field :object_id, class:"form-control"  %>
                </div>
            </div>
        </div>
    <% end %>

<script type="text/javascript">
  $(document).ready(function(){
    $('#transaction_trx_date').datepicker({
        format: "yyyy-mm-dd",
        weekStart: 1,
        language: "en",
        daysOfWeekHighlighted: "0,6",
        todayBtn: true,
        todayHighlight: true,
        firstDay: 1}
    );
    $('#transaction_valuta').datepicker({
        format: "yyyy-mm-dd",
        weekStart: 1,
        language: "en",
        daysOfWeekHighlighted: "0,6",
        todayBtn: true,
        todayHighlight: true,
        firstDay: 1}
    );
  });
</script>

<script>
  document.addEventListener("turbolinks:load", function() {init_map(0);datepicker()})
</script>

app/views/transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Transactions</h1>

<table>
  <thead>
    <tr>
      <th>Account ver</th>
      <th>Account bel</th>
      <th>Valuta</th>
      <th>Status ver</th>
      <th>Status bel</th>
      <th>Status</th>
      <th>Active</th>
      <th>Trx text</th>
      <th>Trx ref</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.account_ver %></td>
        <td><%= transaction.account_bel %></td>
        <td><%= transaction.valuta %></td>
        <td><%= transaction.status_ver %></td>
        <td><%= transaction.status_bel %></td>
        <td><%= transaction.status %></td>
        <td><%= transaction.active %></td>
        <td><%= transaction.trx_text %></td>
        <td><%= transaction.trx_ref %></td>
        <td><%= link_to 'Show', transaction %></td>
        <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
        <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction', new_transaction_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Account ver:</strong>
  <%= @transaction.account_ver %>
</p>

<p>
  <strong>Account bel:</strong>
  <%= @transaction.account_bel %>
</p>

<p>
  <strong>Valuta:</strong>
  <%= @transaction.valuta %>
</p>

<p>
  <strong>Valuta:</strong>
  <%= @transaction.amount %>
</p>

<p>
  <strong>Status ver:</strong>
  <%= @transaction.status_ver %>
</p>

<p>
  <strong>Status bel:</strong>
  <%= @transaction.status_bel %>
</p>

<p>
  <strong>Status:</strong>
  <%= @transaction.status %>
</p>

<p>
  <strong>Active:</strong>
  <%= @transaction.active %>
</p>

<p>
  <strong>Trx text:</strong>
  <%= @transaction.text %>
</p>

<p>
  <strong>Trx text:</strong>
  <%= @transaction.ref %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>