config/routes.rb
Rails.application.routes.draw do

  resources :deputies
  
  #devise_for :users
  resources :charges
  resources :sensors
  resources :idea_crowdratings
  resources :prices
  resources :crits
  resources :idea_ratings
  resources :criterias
  resources :ideas
  resources :plannings
  resources :timetracks
  resources :user_answers
  resources :answers
  resources :questions
  resources :mlikes
  resources :comments
  resources :edition_arcticles
  resources :editions
  resources :qrcodes
  resources :signage_hits
  resources :signage_cals
  get 'rooms/show'

  resources :credentials
  root 'home#index3'
  
  resources :webmasters
  resources :user_tickets
  resources :user_positions
  resources :transactions
  get 'ticketuserview/index'
  get 'ticketuserview/index2'
  get 'users/ticketstatus'
  resources :tickets
  get 'statement/index'

  get 'showcal/index'
  get 'home/nutzung'
  get 'home/index'
  get 'home/index1'
  #get 'home/index1/:ticket_id', to: 'home#index1'
  get 'home/index2'
  get 'home/index3'
  get 'home/index6'
  get 'home/index7'
  get 'home/index8'
  get 'home/index9'
  get 'home/index10'
  get 'home/index11'
  get 'home/index12'
  get 'home/index13'
  get 'home/index14'
  get 'home/index15'
  get 'home/index16'
  get 'home/index17'
  get 'home/index18'
  get 'home/import'
  get 'home/dashboard'
  get 'home/dashboard2'
  get 'home/dashboard_project'
  get 'home/dashboard_data'
  get 'home/dashboard2_data'
  get 'home/dashboard_projectdata'
  get 'home/Umfragen_data'
  get 'home/readsensordata'
  get 'home/writesensordata'
  
  resources :searches
  resources :partner_links
  resources :mstats
  resources :msponsors
  resources :mratings
  resources :mobjects
  resources :mdetails
  resources :mcategories
  resources :mcalendars
  resources :madvisors
  get 'listaccount/index'

  resources :favourits
  resources :emails
  resources :customers
  get 'customer_advisor/index'

  get 'customer_advisor/index2'
  get 'appparams/updateuser'
  
  resources :companies
  resources :appparams
  resources :appointments
  resources :appointment_documents
  resources :accounts
  root 'home#index3'

  #devise_for :users, :controllers => {registrations: 'registrations'}
  #devise_for :users, :controllers => {registrations: 'registrations', passwords: 'passwords', confirmations: "confirmations"}
  devise_for :users, :controllers => {registrations: 'registrations', passwords: 'passwords'}
  
  resources :users
  resources :tests
  
  # mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/signage_hit.rb
class SignageHit < ApplicationRecord
end

app/controllers/signage_hits_controller.rb
class SignageHitsController < ApplicationController
  before_action :set_signage_hit, only: [:show, :edit, :update, :destroy]

  # GET /signage_hits
  # GET /signage_hits.json
  def index
    @signage_hits = SignageHit.all
  end

  # GET /signage_hits/1
  # GET /signage_hits/1.json
  def show
  end

  # GET /signage_hits/new
  def new
    @signage_hit = SignageHit.new
  end

  # GET /signage_hits/1/edit
  def edit
  end

  # POST /signage_hits
  # POST /signage_hits.json
  def create
    @signage_hit = SignageHit.new(signage_hit_params)

    respond_to do |format|
      if @signage_hit.save
        format.html { redirect_to @signage_hit, notice: (I18n.t :act_create) }
        format.json { render :show, status: :created, location: @signage_hit }
      else
        format.html { render :new }
        format.json { render json: @signage_hit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /signage_hits/1
  # PATCH/PUT /signage_hits/1.json
  def update
    respond_to do |format|
      if @signage_hit.update(signage_hit_params)
        format.html { redirect_to @signage_hit, notice: (I18n.t :act_update) }
        format.json { render :show, status: :ok, location: @signage_hit }
      else
        format.html { render :edit }
        format.json { render json: @signage_hit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /signage_hits/1
  # DELETE /signage_hits/1.json
  def destroy
    @signage_hit.destroy
    respond_to do |format|
      format.html { redirect_to signage_hits_url, notice: (I18n.t :act_delete) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_signage_hit
      @signage_hit = SignageHit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def signage_hit_params
      params.require(:signage_hit).permit(:signage_camp_id, :signage_loc_id, :datetime_from)
    end
end

app/views/signage_hits/_form.html.erb
<%= form_for(signage_hit) do |f| %>
  <% if signage_hit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(signage_hit.errors.count, "error") %> prohibited this signage_hit from being saved:</h2>

      <ul>
      <% signage_hit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :signage_camp_id %>
    <%= f.number_field :signage_camp_id %>
  </div>

  <div class="field">
    <%= f.label :signage_loc_id %>
    <%= f.number_field :signage_loc_id %>
  </div>

  <div class="field">
    <%= f.label :datetime_from %>
    <%= f.text_field :datetime_from %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/signage_hits/edit.html.erb
<h1>Editing Signage Hit</h1>

<%= render 'form', signage_hit: @signage_hit %>

<%= link_to 'Show', @signage_hit %> |
<%= link_to 'Back', signage_hits_path %>

app/views/signage_hits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Signage Hits</h1>

<table>
  <thead>
    <tr>
      <th>Signage camp</th>
      <th>Signage loc</th>
      <th>Datetime from</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @signage_hits.each do |signage_hit| %>
      <tr>
        <td><%= signage_hit.signage_camp_id %></td>
        <td><%= signage_hit.signage_loc_id %></td>
        <td><%= signage_hit.datetime_from %></td>
        <td><%= link_to 'Show', signage_hit %></td>
        <td><%= link_to 'Edit', edit_signage_hit_path(signage_hit) %></td>
        <td><%= link_to 'Destroy', signage_hit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Signage Hit', new_signage_hit_path %>

app/views/signage_hits/new.html.erb
<h1>New Signage Hit</h1>

<%= render 'form', signage_hit: @signage_hit %>

<%= link_to 'Back', signage_hits_path %>

app/views/signage_hits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Signage camp:</strong>
  <%= @signage_hit.signage_camp_id %>
</p>

<p>
  <strong>Signage loc:</strong>
  <%= @signage_hit.signage_loc_id %>
</p>

<p>
  <strong>Datetime from:</strong>
  <%= @signage_hit.datetime_from %>
</p>

<%= link_to 'Edit', edit_signage_hit_path(@signage_hit) %> |
<%= link_to 'Back', signage_hits_path %>